export const currenciesOptions = [
  { code: 'USD', name: 'Dólar dos EUA' },
  { code: 'EUR', name: 'Euro' },
  { code: 'GBP', name: 'Libra esterlina' },
  { code: 'CAD', name: 'Dólar canadense' },
  { code: 'AUD', name: 'Dólar australiano' },
  { code: 'JPY', name: 'Iene japonês' },
  { code: 'INR', name: 'Rúpia indiana' },
  { code: 'NZD', name: 'Dólar neozelandês' },
  { code: 'CHF', name: 'Franco suíço' },
  { code: 'ZAR', name: 'Rand sul-africano' },
  { code: 'RUB', name: 'Rublo russo' },
  { code: 'BGN', name: 'Lev búlgaro' },
  { code: 'SGD', name: 'Dólar de Cingapura' },
  { code: 'HKD', name: 'Dólar de Hong Kong' },
  { code: 'SEK', name: 'Coroa sueca' },
  { code: 'THB', name: 'Baht tailandês' },
  { code: 'HUF', name: 'Forint húngaro' },
  { code: 'CNY', name: 'Yuan Renminbi chinês' },
  { code: 'NOK', name: 'Coroa norueguesa' },
  { code: 'MXN', name: 'Peso mexicano' },
  { code: 'DKK', name: 'Coroa dinamarquesa' },
  { code: 'MYR', name: 'Ringgit malaio' },
  { code: 'PLN', name: 'Zloty polonês' },
  { code: 'BRL', name: 'Real brasileiro' },
  { code: 'PHP', name: 'Peso filipino' },
  { code: 'IDR', name: 'Rupia indonésia' },
  { code: 'CZK', name: 'Coroa checa' },
  { code: 'AED', name: 'Dirham dos Emirados' },
  { code: 'TWD', name: 'Novo dólar taiwanês' },
  { code: 'KRW', name: 'Won sul-coreano' },
  { code: 'ILS', name: 'Shekel israelense' },
  { code: 'ARS', name: 'Peso argentino' },
  { code: 'CLP', name: 'Peso chileno' },
  { code: 'EGP', name: 'Libra egípcia' },
  { code: 'TRY', name: 'Lira turca' },
  { code: 'RON', name: 'Leu romeno' },
  { code: 'SAR', name: 'Rial saudita' },
  { code: 'PKR', name: 'Rúpia paquistanesa' },
  { code: 'COP', name: 'Peso colombiano' },
  { code: 'IQD', name: 'Dinar iraquiano' },
  { code: 'XAU', name: 'Onça de ouro' },
  { code: 'FJD', name: 'Dólar fijiano' },
  { code: 'KWD', name: 'Dinar kuwaitiano' },
  { code: 'BAM', name: 'Marco conversível bósnio' },
  { code: 'ISK', name: 'Coroa islandesa' },
  { code: 'MAD', name: 'Dirham marroquino' },
  { code: 'HRK', name: 'Kuna croata' },
  { code: 'VND', name: ' Dong vietnamita' },
  { code: 'JMD', name: 'Dólar jamaicano' },
  { code: 'JOD', name: 'Dinar jordaniano' },
  { code: 'DOP', name: 'Peso dominicano' },
  { code: 'PEN', name: 'Sol peruano' },
  { code: 'CRC', name: 'Colón costarriquenho' },
  { code: 'BHD', name: 'Dinar baremita ' },
  { code: 'BDT', name: 'Taka bengalês' },
  { code: 'DZD', name: 'Dinar argelino' },
  { code: 'KES', name: 'Xelim queniano' },
  { code: 'XAG', name: 'Onça de prata' },
  { code: 'LKR', name: 'Rúpia cingalesa' },
  { code: 'OMR', name: 'Rial omanense' },
  { code: 'QAR', name: 'Rial do Qatar' },
  { code: 'XOF', name: 'Franco CFA' },
  { code: 'IRR', name: 'Rial iraniano' },
  { code: 'XCD', name: 'Dólar do Caribe Oriental' },
  { code: 'TND', name: 'Dinar tunisiano' },
  { code: 'TTD', name: 'Dólar de Trinidad e Tobago' },
  { code: 'XPF', name: 'Franco CFP' },
  { code: 'EEK', name: 'Coroa estoniana' },
  { code: 'ZMK', name: 'Kwacha zambiano' },
  { code: 'ZMW', name: 'Kwacha zambiano' },
  { code: 'BBD', name: 'Dólar barbadiano' },
  { code: 'NGN', name: 'Naira nigeriano' },
  { code: 'LBP', name: 'Libra libanesa' },
  { code: 'XAF', name: 'Franco CFA centroafricano BEAC' },
  { code: 'MUR', name: 'Rupia mauriciana' },
  { code: 'XPT', name: 'Onça de platina' },
  { code: 'BSD', name: 'Dólar bahamense' },
  { code: 'ALL', name: 'Lek albanês' },
  { code: 'UYU', name: 'Peso uruguaio' },
  { code: 'BMD', name: 'Dólar bermudense' },
  { code: 'LVL', name: 'Lat letão' },
  { code: 'UAH', name: 'Hryvna ucraniano' },
  { code: 'GTQ', name: 'Quetzal guatemalteco' },
  { code: 'XDR', name: 'Direitos de saque especiais do FMI' },
  { code: 'BWP', name: 'Pula botsuano' },
  { code: 'BOB', name: 'Bolíviano da Bolívia' },
  { code: 'CUP', name: 'Peso cubano' },
  { code: 'PYG', name: 'Guarani paraguaio' },
  { code: 'HNL', name: 'Lempira hondurenha' },
  { code: 'LTL', name: 'Litas lituana' },
  { code: 'ZWD', name: 'Dólar zimbabuano' },
  { code: 'NIO', name: 'Córdoba nicaraguense' },
  { code: 'RSD', name: 'Dinar sérvio' },
  { code: 'NPR', name: 'Rúpia nepalesa' },
  { code: 'HTG', name: 'Gourde haitiano' },
  { code: 'PAB', name: 'Balboa panamenho' },
  { code: 'SVC', name: 'Colón salvadorenho' },
  { code: 'GYD', name: 'Dólar guianense' },
  { code: 'KYD', name: 'Dólar caimanês' },
  { code: 'TZS', name: 'Xelim tanzaniano' },
  { code: 'CNH', name: 'Chinese Yuan Renminbi Offshore' },
  { code: 'CVE', name: 'Escudo caboverdiano' },
  { code: 'FKP', name: 'Libra das Malvinas' },
  { code: 'ANG', name: 'Florim holandês' },
  { code: 'UGX', name: 'Xelim ugandês' },
  { code: 'MGA', name: 'Ariary malgaxe' },
  { code: 'GEL', name: 'Lari georgiano' },
  { code: 'ETB', name: 'Birr etíope' },
  { code: 'MDL', name: 'Leu moldavo' },
  { code: 'VUV', name: 'Vatu de Ni-Vanuatu' },
  { code: 'SYP', name: 'Libra síria' },
  { code: 'BND', name: 'Dólar bruneano' },
  { code: 'KHR', name: 'Riel cambojano' },
  { code: 'NAD', name: 'Dólar namibiano' },
  { code: 'MKD', name: 'Dinar macedônio' },
  { code: 'AOA', name: 'Kwanza angolano' },
  { code: 'PGK', name: 'Kina de Papua Nova Guiné' },
  { code: 'MMK', name: 'Kyat birmanês' },
  { code: 'KZT', name: 'Tenge cazaquistanês' },
  { code: 'MOP', name: 'Pataca de Macau' },
  { code: 'MZN', name: 'Metical moçambicano' },
  { code: 'LYD', name: 'Dinar líbio' },
  { code: 'SLL', name: 'Leone de Serra Leoa' },
  { code: 'GNF', name: 'Franco guineense' },
  { code: 'BYN', name: 'Rublo bielorrusso' },
  { code: 'BYR', name: 'Rublo bielorrusso' },
  { code: 'GMD', name: 'Dalasi gambiano' },
  { code: 'AWG', name: 'Florim arubano ou holandês' },
  { code: 'AMD', name: 'Dram armênio' },
  { code: 'YER', name: 'Rial iemenita' },
  { code: 'LAK', name: 'Kip laosiano' },
  { code: 'WST', name: 'Tala samoana' },
  { code: 'MWK', name: 'Kwacha malawiana' },
  { code: 'KPW', name: 'Won norte-coreano' },
  { code: 'BIF', name: 'Franco burundês' },
  { code: 'DJF', name: 'Franco djibutiano' },
  { code: 'MNT', name: 'Tughrik mongol' },
  { code: 'UZS', name: 'Som uzbeque' },
  { code: 'TOP', name: "Pa'anga de Tonga" },
  { code: 'SCR', name: 'Rúpia seichelense' },
  { code: 'KGS', name: 'Som quirguistanês' },
  { code: 'BTN', name: 'Ngultrum butanês' },
  { code: 'SBD', name: 'Dólar das Ilhas Salomão' },
  { code: 'GIP', name: 'Libra de Gibraltar' },
  { code: 'RWF', name: 'Franco ruandês' },
  { code: 'CDF', name: 'Franco congolês' },
  { code: 'MVR', name: 'Rufiyaa maldiva' },
  { code: 'MRU', name: 'Ouguiya mauritano' },
  { code: 'ERN', name: 'Nakfa eritreana' },
  { code: 'SOS', name: 'Xelim somaliano' },
  { code: 'SZL', name: 'Lilangeni swazi' },
  { code: 'TJS', name: 'Somoni tajiquistanês' },
  { code: 'LRD', name: 'Dólar liberiano' },
  { code: 'LSL', name: 'Loti do Basotho' },
  { code: 'SHP', name: 'Libra de Santa Helena' },
  { code: 'STN', name: 'Dobra de São Tomé' },
  { code: 'KMF', name: 'Franco comorense' },
  { code: 'SPL', name: 'Luigino de Seborga' },
  { code: 'TMT', name: 'Manat turcomano' },
  { code: 'SRD', name: 'Dólar do Suriname' },
  { code: 'IMP', name: 'Libra da Ilha de Man' },
  { code: 'JEP', name: 'Libra de Jersey' },
  { code: 'TVD', name: 'Dólar Tuvaluano' },
  { code: 'GGP', name: 'Libra de Guernsey' },
  { code: 'AFN', name: 'Afegane afegão' },
  { code: 'AZN', name: 'Manat azeri' },
  { code: 'BZD', name: 'Dólar belizenho' },
  { code: 'CUC', name: 'Peso conversível cubano' },
  { code: 'GHS', name: 'Cedi ganês' },
  { code: 'SDG', name: 'Libra sudanesa' },
  { code: 'VES', name: 'Bolívar venezuelano' },
  { code: 'VEF', name: 'Bolívar venezuelano' },
  { code: 'XPD', name: 'Onça de paládio' },
  { code: 'XBT', name: 'Bitcoin' },
  { code: 'ADA', name: 'Cardano' },
  { code: 'BCH', name: 'Bitcoin Cash' },
  { code: 'DOGE', name: 'Dogecoin' },
  { code: 'DOT', name: 'Polkadot' },
  { code: 'ETH', name: 'Ether' },
  { code: 'LINK', name: 'Chainlink' },
  { code: 'LTC', name: 'Litecoin' },
  { code: 'LUNA', name: 'Terra' },
  { code: 'UNI', name: 'Uniswap' },
  { code: 'XLM', name: 'Stellar Lumen' },
  { code: 'XRP', name: 'Ripple' },
  { code: 'ATS', name: 'Austrian Schilling (obsoleta)' },
  { code: 'AZM', name: 'Azerbaijani Manat (obsoleta)' },
  { code: 'BEF', name: 'Belgian Franc (obsoleta)' },
  { code: 'CYP', name: 'Cypriot Pound (obsoleta)' },
  { code: 'DEM', name: 'German Deutsche Mark (obsoleta)' },
  { code: 'ESP', name: 'Spanish Peseta (obsoleta)' },
  { code: 'FIM', name: 'Finnish Markka (obsoleta)' },
  { code: 'FRF', name: 'French Franc (obsoleta)' },
  { code: 'GHC', name: 'Ghanaian Cedi (obsoleta)' },
  { code: 'GRD', name: 'Greek Drachma (obsoleta)' },
  { code: 'IEP', name: 'Irish Pound (obsoleta)' },
  { code: 'ITL', name: 'Italian Lira (obsoleta)' },
  { code: 'LUF', name: 'Luxembourg Franc (obsoleta)' },
  { code: 'MGF', name: 'Malagasy Franc (obsoleta)' },
  { code: 'MRO', name: 'Ouguiya mauritano (obsoleta)' },
  { code: 'MTL', name: 'Maltese Lira (obsoleta)' },
  { code: 'MZM', name: 'Mozambican Metical (obsoleta)' },
  { code: 'NLG', name: 'Dutch Guilder (obsoleta)' },
  { code: 'PTE', name: 'Portuguese Escudo (obsoleta)' },
  { code: 'ROL', name: 'Romanian Leu (obsoleta)' },
  { code: 'SDD', name: 'Sudanese Dinar (obsoleta)' },
  { code: 'SIT', name: 'Slovenian Tolar (obsoleta)' },
  { code: 'SKK', name: 'Slovak Koruna (obsoleta)' },
  { code: 'SRG', name: 'Surinamese Guilder (obsoleta)' },
  { code: 'STD', name: 'Dobra de São Tomé (obsoleta)' },
  { code: 'TMM', name: 'Turkmenistani Manat (obsoleta)' },
  { code: 'TRL', name: 'Turkish Lira (obsoleta)' },
  { code: 'VAL', name: 'Vatican City Lira (obsoleta)' },
  { code: 'VEB', name: 'Bolívar venezuelano (obsoleta)' },
  { code: 'XEU', name: 'European Currency Unit (obsoleta)' },
]
